version: '3'

services:
  app:
    ports:
      - "80:80"
    tty: true
    privileged: true
    build: ./containers
    container_name: batch
    # depends_on:
    #   - mysql
    command: ["/sbin/init"]
    volumes:
      - ./containers/app/nginx.conf:/etc/nginx/nginx.conf
      - ./containers/app/conf.d:/etc/nginx/conf.d
      - ./containers/app/php.ini:/etc/php.ini
      - ./batch:/home/batch
  
  # cron:
  #   build: ./containers/cron
  #   container_name: cron
  #   volumes:
  #     - ./batch:/home/batch

  # mysql:
  #   image: mysql:8.0
  #   platform: linux/x86_64
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: example_app
  #     MYSQL_USER: sail
  #     MYSQL_PASSWORD: password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql:/var/lib/mysql
